name: Lint

on:
  push:

jobs:
  build:
    name: Run Github Super Linter action

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Lint
        uses: github/super-linter@v2.0.0
